AppSettings:
  SiteTitle: Music Store
  CacheDbResults: true
Logging: 
  IncludeScopes: false
  LogLevel: 
    Default: Information
    System: Information
    Microsoft: Information
    Steeltoe.Discovery: Debug
    Pivotal.Discovery: Debug

eureka:
  client:
    serviceUrl: http://localhost:8761/eureka/
    validate_certificates: false
mysql:
  client:
    server: localhost
    sslmode: none
management: 
  endpoints: 
    path: /cloudfoundryapplication
    cloudfoundry: 
      validateCertificates: false
